name: Publish Module

on:
  push:
    branches: [main, beta]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Init Terraform
      run: terraform init
    - name: Install Plugins
      run: npm install --save-dev @semantic-release/changelog @semantic-release/git    
    - name: Terraform Format
      run: terraform fmt -check
    - name: Terraform Validate
      run: terraform validate -no-color  
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release